import { randomBytes } from "node:crypto";
import type { CreateInstanceInput, DatabaseSpec, RdiPipelineSpec, RdiSpec } from "./types.js";

const MAX_RDI_SLUG = 30;
/** Memory (GB) for the synthesized RDI pipeline-state database. */
const RDI_STATE_MEMORY_GB = 1;

/** Slugify + validate the RDI short name. The deployment prefix is added later. */
export function normalizeRdiName(raw: unknown): string {
  const slug = String(raw ?? "")
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, MAX_RDI_SLUG)
    .replace(/-+$/g, "");
  if (!slug) throw new Error("RDI name is required");
  if (!/^[a-z]/.test(slug)) throw new Error("RDI names must start with a letter");
  return slug;
}

/** The RDI runtime name within the project: `<deploymentPrefix>-<slug>`. */
export function rdiFullName(deploymentPrefix: string, name: string): string {
  return `${deploymentPrefix}-${name}`;
}

/** Name of the synthesized pipeline-state database for an RDI instance. */
export function rdiStateDbName(rdiName: string): string {
  return `${rdiName}-state`;
}

/** Validate + default the RDI spec, or null when no RDI is configured. Pure. */
export function normalizeRdi(input: { rdi?: RdiSpec }): Required<Omit<RdiSpec, "target">> & {
  target?: string;
} | null {
  const rdi = input.rdi;
  if (!rdi) return null;
  const name = normalizeRdiName(rdi.name);
  const seenSources = new Set<string>();
  const pipelines: RdiPipelineSpec[] = (rdi.pipelines || []).map((p) => {
    const source = String(p.source ?? "").trim();
    if (!source) throw new Error("An RDI pipeline needs a source");
    if (seenSources.has(source)) throw new Error(`RDI pipeline sources must be unique (${source})`);
    seenSources.add(source);
    return {
      source,
      tables: (p.tables || []).map((t) => ({
        table: String(t.table ?? "").trim(),
        key_prefix: String(t.key_prefix ?? "").trim() || undefined,
      })),
    };
  });
  return {
    name,
    machine_type: String(rdi.machine_type ?? "").trim() || "n2-standard-4",
    target: rdi.target ? String(rdi.target).trim() : undefined,
    pipelines,
  };
}

/**
 * Return a shallow copy of `input` whose clusters carry the synthesized RDI
 * pipeline-state database. The state DB is a tool-created database (its password
 * is generated here and injected into RDI), created in the cluster that hosts the
 * RDI target database. Idempotent: any prior `rdi_internal` databases are dropped
 * first, so re-running (e.g. on a config round-trip) never duplicates it.
 *
 * Generates a fresh password each call, so call this exactly ONCE at create time
 * and persist the result; workspace generation must read the persisted state DB
 * rather than re-synthesizing it.
 */
export function withRdiInternalDatabases(input: CreateInstanceInput): CreateInstanceInput {
  const clusters = (input.clusters || []).map((c) => ({
    ...c,
    databases: (c.databases || []).filter((d) => !d.rdi_internal),
  }));
  const rdi = normalizeRdi(input);
  if (rdi?.target) {
    const idx = clusters.findIndex((c) => (c.databases || []).some((d) => d.name === rdi.target));
    if (idx >= 0) {
      const stateDb: DatabaseSpec = {
        name: rdiStateDbName(rdi.name),
        memory_gb: RDI_STATE_MEMORY_GB,
        replication: false,
        port: 13000,
        password: randomBytes(15).toString("base64url"),
        rdi_internal: true,
      };
      clusters[idx] = { ...clusters[idx], databases: [...(clusters[idx].databases || []), stateDb] };
    }
  }
  return { ...input, clusters };
}

/** Cloud SQL source short-names referenced by any RDI pipeline. */
export function rdiSourceNames(input: { rdi?: RdiSpec }): Set<string> {
  const set = new Set<string>();
  const rdi = normalizeRdi(input);
  for (const p of rdi?.pipelines || []) set.add(p.source);
  return set;
}

/**
 * Render a starter RDI pipeline config (config.yaml + per-table jobs) from the
 * normalized spec. Sources reference the injected `SQL_<slug>_*` env; the target
 * references the injected `RDI_TARGET_*` env. Returned base64 for transport as a
 * single tfvars string.
 */
export function renderRdiPipelineConfig(rdi: NonNullable<ReturnType<typeof normalizeRdi>>): string {
  const envSlug = (n: string) => n.toUpperCase().replace(/[^A-Z0-9]+/g, "_").replace(/^_+|_+$/g, "");
  const lines: string[] = [];
  lines.push("# Generated by redis-ent-wizard — starter RDI pipeline config.");
  lines.push("sources:");
  if (rdi.pipelines.length === 0) {
    lines.push("  {} # no source wired — configure a pipeline before deploying");
  }
  for (const p of rdi.pipelines) {
    const s = envSlug(p.source);
    lines.push(`  ${p.source}:`);
    lines.push("    type: cdc");
    lines.push("    connection:");
    lines.push(`      host: \${SQL_${s}_HOST}`);
    lines.push(`      port: \${SQL_${s}_PORT}`);
    lines.push(`      database: \${SQL_${s}_DB}`);
    lines.push(`      user: \${SQL_${s}_USER}`);
    lines.push(`      password: \${SQL_${s}_PASSWORD}`);
    if (p.tables && p.tables.length) {
      lines.push("    tables:");
      for (const t of p.tables) {
        lines.push(`      - table: ${t.table}`);
        lines.push(`        key_prefix: ${t.key_prefix || t.table}`);
      }
    }
  }
  lines.push("target:");
  lines.push("  connection:");
  lines.push("    host: ${RDI_TARGET_HOST}");
  lines.push("    port: ${RDI_TARGET_PORT}");
  lines.push("    password: ${RDI_TARGET_PASSWORD}");
  return Buffer.from(lines.join("\n") + "\n", "utf8").toString("base64");
}
